GET http://localhost:8080/posts 
Authorization: autherization eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT2xlT2xlT2xlIiwiaWF0IjoxNjA4NTc2MTU3fQ.8FP9qfvJKpk8KUnnBKzOPrPpRnIUYvoxsjRbjim533c

###
GET http://localhost:8080/test
Authorization: autherization eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT2xlT2xlT2xlIiwiaWF0IjoxNjA4NTc3MTgxfQ.b3LT1ClidtdZ6fVVRocfiwJBseEVX-pq3o6yhdMB9mw

###
#POST
POST http://localhost:8080/register/
Content-Type: application/json

{
    "username":"OleOlesOle",
    "password": "123456123456",
    "email":"asdasd@asdasd.com"
}

### 
POST http://localhost:8080/login
Content-Type: application/json

{
    "username":"OleOleOle",
    "password": "123456123456"                                  
}

###
GET http://localhost:8080/logout/