GET http://localhost:8080/posts 
Authorization: autherization eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT2xlT2xlT2xlIiwiaWF0IjoxNjA4MjAxODEwLCJleHAiOjE2MDgyMDE4MjB9.mWu0IeYJhdTtpiioB0nBTz3IVFq2AC_axPWl67v8rLU


###
#POST
POST http://localhost:8080/register/
Content-Type: application/json

{
    "username":"OleOleOle",
    "password": "123456123456",
    "email":"asdasd@asdasd.com"
}

### 
POST http://localhost:8080/login
Content-Type: application/json

{
    "username":"OleOleOle",
    "email":"asdasd@asdasd.com",
    "password": "123456123456"
}

###
POST http://localhost:8080/login/
Content-Type: application/json
{
    "username":"tata"
}